sonar.projectKey=wlwlwlwl57_cangchu_1
sonar.organization=wlwlwlwl57
sonar.host.url=https://sonarcloud.io

sonar.sources=hou/cangchu/src/main/java,qian/Cangchu_qian/src
sonar.tests=hou/cangchu/src/test/java
sonar.java.binaries=hou/cangchu/target/classes
sonar.java.test.binaries=hou/cangchu/target/test-classes

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/target/**,**/build/**,**/node_modules/**,**/.idea/**,**/.vscode/**,**/*.log,**/*.tmp,**/mvw*,**/package-lock.json,**/.mvn/**,**/dist/**

sonar.test.exclusions=**/dto/**,**/entity/**,**/CangchuApplication.java

sonar.coverage.exclusions=**/dto/**,**/entity/**,**/CangchuApplication.java,**/repository/**,**/exception/**

sonar.scm.exclusions=**/package-lock.json,**/mvnw*,**/.mvn/**

sonar.analysis.cache.enabled=true
